apiVersion: v1
kind: Pod
metadata:
  namespace: unixpense
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  - name: kubectl
    image: quay.io/clastix/kubectl:v1.24
    command:
    - cat
    tty: true
  volumes:
  - name: kaniko-secret
    secret:
      secretName: unixpense-svc-regcred
      items:
      - key: .dockerconfigjson
        path: config.json