kind: ConfigMap
apiVersion: v1
metadata:
  name: unixpense-svc-config
  namespace: unixpense
data:
  PORT: '$PORT'
  NODE_ENV: $NODE_ENV
  LOG_LEVEL: $LOG_LEVEL
  UNIXPENSE_HOST: $UNIXPENSE_HOST
  UNIXPENSE_HOST_PREFIX: $UNIXPENSE_HOST_PREFIX
  LOKI_HOST: $LOKI_HOST