apiVersion: batch/v1
kind: CronJob
metadata:
  name: unixpense-cron
  namespace: unixpense
spec:
  schedule: "$CRONTAB"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600 # 10 minutes
      backoffLimit: 2
      ttlSecondsAfterFinished: 5
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: refresh-sh
            configMap:
              name: refresh-sh
              defaultMode: 0555
          containers:
          - name: mariadb-client
            image: mariadb:latest
            env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
            - name: GMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: oauth2-authenticated-emails
                  key: authenticated-emails
            envFrom:
            - secretRef:
                name: telegram-secret
            volumeMounts:
              - mountPath: /usr/sh
                name: refresh-sh
            command:
              - /bin/bash
              - -ec
              - /usr/sh/refresh.sh