apiVersion: batch/v1
kind: CronJob
metadata:
  name: unixpense-cron
  namespace: unixpense
spec:
  schedule: "$CRONTAB"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 5
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: refresh-sh
            configMap:
              name: unixpense-refresh-sh
              defaultMode: 0555
          containers:
          - name: mariadb-client
            image: mariadb:latest
            env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
            envFrom:
            - secretRef:
                name: telegram-secret
            volumeMounts:
              - mountPath: /usr/sh
                name: refresh-sh
            command:
            - /bin/sh
            - -ec
            - /usr/sh/refresh.sh