apiVersion: batch/v1
kind: CronJob
metadata:
  name: unixpense-cron
  namespace: unixpense
spec:
  schedule: "$CRONTAB"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 5
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: mariadb-client
            image: mariadb:latest
            env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
            command:
            - /bin/sh
            - -ec
            - |
              apt-get -qy update; apt-get -qy -o=Dpkg::Use-Pty=0 install curl

              ACCESS_TOKEN_QUERY="\
                SELECT access_token
                FROM google_oauth2_tokens
                WHERE user_email='$GMAIL_ADDRESS'"

              ACCESS_TOKEN=$(mariadb unixpense \
                -h mariadb-service.unixpense.svc.cluster.local \
                -u$MARIADB_USER \
                -p$MARIADB_PASSWORD \
                -se "$ACCESS_TOKEN_QUERY")

              TRANSACTION_IDS=$(curl -s \
                -X GET "http://unixpense-svc-service.unixpense.svc.cluster.local:8000/api/transactions/gmail/get/ids/skip_depth/100?skip_saved=true" \
                -H "X-User-Email: $GMAIL_ADDRESS" \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -H "Accept: application/json")

              RESULT=$(curl -s \
                -X POST "http://unixpense-svc-service.unixpense.svc.cluster.local:8000/api/transactions/gmail/save" \
                -H "X-User-Email: $GMAIL_ADDRESS" \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d $TRANSACTION_IDS)