apiVersion: apps/v1
kind: Deployment
metadata:
  name: unixpense-svc
  namespace: unixpense
  labels:
    app: unixpense-svc
spec:
  selector:
    matchLabels:
      app: unixpense-svc
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
  template:
    metadata:
      labels:
        app: unixpense-svc
    spec:
      volumes:
      - name: mariadb-volume
        persistentVolumeClaim:
          claimName: mariadb-pvc
      securityContext:
        runAsUser: 1000
      containers:
      - name: mariadb
        image: mariadb:latest
        resources:
          requests:
            cpu: 300m
            memory: 75Mi
          limits:
            cpu: 500m
            memory: 150Mi
        envFrom:
        - secretRef:
            name: mariadb-secret
        ports:
        - containerPort: 3306
          name: mariadb-port
        volumeMounts:
        - name: mariadb-volume
          mountPath: /var/lib/mysql
      - name: unixpense-svc
        image: nikolayrk/unixpense-svc:$latest
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 350m
            memory: 350Mi
        startupProbe:
          httpGet:
            path: /healthz
            port: $PORT
          initialDelaySeconds: 100
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: $PORT
          initialDelaySeconds: 100
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /alivez
            port: $PORT
          initialDelaySeconds: 100
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - containerPort: $PORT
        envFrom:
        - configMapRef:
            name: unixpense-svc-config
        - secretRef:
            name: mariadb-secret