apiVersion: apps/v1
kind: Deployment
metadata:
  name: unixpense-svc
  namespace: unixpense
  labels:
    app: unixpense-svc
spec:
  selector:
    matchLabels:
      app: unixpense-svc
  revisionHistoryLimit: 0
  replicas: 2
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
  template:
    metadata:
      labels:
        app: unixpense-svc
    spec:
      securityContext:
        runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfig
      containers:
      - name: unixpense-svc
        image: $DOCKER_REGISTRY_URL/$DOCKER_REPO:$latest
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
          limits:
            cpu: 350m
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 120
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /alivez
            port: http
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - name: http
          containerPort: $PORT
        envFrom:
        - configMapRef:
            name: unixpense-svc-config
        - secretRef:
            name: mariadb-secret
        - secretRef:
            name: google-cred