apiVersion: apps/v1
kind: Deployment
metadata:
  name: unixpense-svc
  namespace: unixpense
  labels:
    app: unixpense-svc
spec:
  selector:
    matchLabels:
      app: unixpense-svc
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 0
         maxUnavailable: 1
  template:
    metadata:
      labels:
        app: unixpense-svc
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: unixpense-svc
        image: nikolayrk/unixpense-svc:$latest
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 350m
            memory: 350Mi
        startupProbe:
          httpGet:
            path: /healthz
            port: $PORT
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: $PORT
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /alivez
            port: $PORT
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 10
        ports:
        - containerPort: $PORT
        envFrom:
        - configMapRef:
            name: unixpense-svc-config
        - secretRef:
            name: mariadb-cred
        - configMapRef:
            name: mariadb-config