apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: unixpense
  name: unixpense-svc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-url: "http://unixpense-auth-service.unixpense.svc.cluster.local:4180$UNIXPENSE_HOST_PREFIX/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host$UNIXPENSE_HOST_PREFIX/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  rules:
  - host: $UNIXPENSE_HOST
    http:
      paths:
      - path: $UNIXPENSE_HOST_PREFIX/(?!oauth2)(api|swagger)(?:$|/)(.*) # Protect /api and /swagger, but not /oauth2
        pathType: Prefix
        backend:
          service:
            name: unixpense-svc-service
            port:
              name: http