apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unixpense
  name: mariadb-pvc
spec:
  storageClassName: $MARIADB_VOLUME_STORAGE_CLASS_NAME
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"