apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: unixpense
  labels:
    app: unixpense-db
spec:
  selector:
    app: unixpense-db
  ports:
  - name: mariadb
    port: 3306
    targetPort: mariadb-port
    protocol: TCP