apiVersion: apps/v1
kind: Deployment
metadata:
  name: unixpense-svc
  namespace: unixpense
  labels:
    app: unixpense-svc
spec:
  selector:
    matchLabels:
      app: unixpense-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: unixpense-svc
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: app
        image: DOCKER_REPO:BUILD_NUMBER # Populated from environmental variables via Jenkins Job
        envFrom:
        - configMapRef:
            name: unixpense-svc-config
        - secretRef:
            name: unixpense-svc-regcred
        - secretRef:
            name: unixpense-svc-googlecred
        - secretRef:
            name: unixpense-svc-dbcred