replicaCount: 1
revisionHistoryLimit: 0
maxSurge: 1
maxUnavailable: 1

securityContext:
  runAsUser: 1000

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 350m
    memory: 256Mi

startupProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 30

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

service:
  port: 8000

metallb:
  enabled: true
  namespace: metallb
  ipAddressPool:
    name: default-pool
    addresses:
    - "192.168.0.50-192.168.0.50"
  l2Advertisement:
    name: default-advertisement
    ipAddressPools:
    - default-pool

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
  host: staging.unixpense-svc.local
  pathType: ImplementationSpecific

mariadb:
  auth:
    database: "unixpense"
    username: test
    password: test
  primary:
    persistence:
      enabled: false

google:
  clientId: client_id
  clientSecret: client_secret
migrations:
  image:
    tag: latest
