apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unixpense-svc.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  VERSION: {{ .Chart.AppVersion | quote }}
  PORT: {{ .Values.service.port | quote }}
  NODE_ENV: {{ (.Values.config).nodeEnv | default "" | quote }}
  LOG_LEVEL: {{ (.Values.config).logLevel | default "" | quote }}
  UNIXPENSE_HOST: {{ (.Values.ingress).host | default "" | quote }}
  {{- if (.Values.config).unixpenseHostPrefix }}
  UNIXPENSE_HOST_PREFIX: {{ (.Values.config).unixpenseHostPrefix | quote }}
  {{- end }}
  {{- if (.Values.config).lokiHost }}
  LOKI_HOST: {{ (.Values.config).lokiHost | quote }}
  {{- end }}