apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unixpense-svc.fullname" . }}-dockerconfig
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.dockerRegistry.url }}": {
          "auth": "{{ printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc }}"
        }
      }
    }