apiVersion: v1
kind: Secret
metadata:
  name: google-cred
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- $oauth2Proxy := index .Values "oauth2-proxy" }}
  GOOGLE_OAUTH2_CLIENT_ID: {{ $oauth2Proxy.config.clientID | b64enc }}
  GOOGLE_OAUTH2_CLIENT_SECRET: {{ $oauth2Proxy.config.clientSecret | b64enc }}