apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unixpense-svc.fullname" . }}-google-cred
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  GOOGLE_OAUTH2_CLIENT_ID: {{ .Values.google.clientId | b64enc }}
  GOOGLE_OAUTH2_CLIENT_SECRET: {{ .Values.google.clientSecret | b64enc }}