{{- if (.Values.run_integration_tests) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "unixpense-svc.fullname" . }}-integration-tests
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "unixpense-svc.fullname" . }}
    integration_tests: "true" # Used in /sh/report_integration_tests_job_status.sh
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: tests
        image: debian:bullseye-slim
        workingDir: /usr/src
        command: 
          - /bin/bash
          - ./sh/run_integration_tests_job.sh
        env:
          - name: SERVICE_URI_INTERNAL
            value: "{{ include "unixpense-svc.fullname" $ }}-app:{{ .Values.service.port }}"
          - name: UNIXPENSE_HOST
            value: "{{ .Values.ingress.host }}"
          - name: MARIADB_HOST
            value: "{{ .Release.Name }}-mariadb"
          - name: MARIADB_PORT
            value: "{{ .Values.mariadb.primary.service.ports.mysql | default 3306 }}"
          - name: MARIADB_USER
            value: "{{ .Values.mariadb.auth.username }}"
          - name: MARIADB_PASSWORD
            value: "{{ .Values.mariadb.auth.password }}"
          - name: MARIADB_DATABASE
            value: "{{ .Values.mariadb.auth.database }}"
        volumeMounts:
          - name: app-source
            mountPath: /usr/src
      volumes:
      - name: app-source
        hostPath:
          path: /usr/src # From ./kind-config.yaml
          type: Directory
      hostAliases:
        - ip: "{{ regexReplaceAll "-.*" (index .Values.metallb.ipAddressPool.addresses 0) "" }}"
          hostnames:
          - "{{ .Values.ingress.host }}"
      restartPolicy: Never
{{- end }}