apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MARIADB_HOST: "{{ .Release.Name }}-mariadb"
  MARIADB_PORT: "{{ .Values.mariadb.primary.service.ports.mysql | default 3306 }}"
  MARIADB_USER: "{{ .Values.mariadb.auth.username }}"
  MARIADB_PASSWORD: "{{ .Values.mariadb.auth.password }}"
  MARIADB_DATABASE: "{{ .Values.mariadb.auth.database }}"
