{{- if .Values.test.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unixpense-svc.fullname" . }}-mock-oauth2-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: mock-oauth2-server
  annotations:
spec:
  selector:
    app: mock-oauth2-server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
{{- end }}