apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "myapp.fullname" . }}
spec:
  selector:
    app: {{ include "myapp.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP