def runBashFile(filePath) {
    sh "chmod +x ${filePath} && ${filePath}"
}

pipeline {
    agent any
	environment {
        NODE_ENV = 'production'
        KUBERNETES_NAMESPACE = 'unixpense'
	}
    stages {
        stage('Init') {
            agent {
                kubernetes {
                    containerTemplate(name: 'kubectl',
                        image: 'quay.io/clastix/kubectl:v1.24',
                        command: 'cat',
                        ttyEnabled: true)
                }
            }
            steps {
                container('kubectl') {
                    withCredentials([usernameColonPassword(
                        credentialsId: 'docker-regcred',
                        variable: 'DOCKER_REGISTRY_CREDENTIALS')]) {
                        withCredentials([file(
                            credentialsId: 'kubeconfig',
                            variable: 'KUBECONFIG')]) {
                                runBashFile 'cicd/jenkins/init.sh'
                        }
                    }
                }
            }
        }
        stage('Prepare Environment') {
            agent {
                kubernetes {
                    yamlFile './cicd/jenkins/agentPod.yaml'
                }
            }
            stages {
                stage('Build') {
                    steps {
                        container('kaniko') {
                            ansiColor('xterm') {
                                runBashFile './cicd/jenkins/build.sh'
                            }
                        }
                    }
                }
                stage('Deploy') {
                    steps {
                        container('kubectl') {
                            withCredentials([file(
                                credentialsId: 'kubeconfig',
                                variable: 'KUBECONFIG')]) {
                                    runBashFile './cicd/jenkins/deploy.sh'
                            }
                        }
                    }
                }
            }
        }
    }
}