name: Generage Coverage Badges

on: 
  push:
    branches:
      - develop
    paths-ignore:
      - '**/README.md'

permissions:
  contents: write

jobs:
  run-coverage-tests:
    name: Run tests
    uses: ./.github/workflows/run_tests_reusable.yml
    with:
      NODE_ENV: test_coverage
      up-flags: "--build --abort-on-container-exit"
      services: coverage_tests
      with-bridge-network: true
      artifacts-path: /home/

  generate:
    name: Generate coverage badge
    runs-on: ubuntu-latest
    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v4
      with:
        path: coverage/
    - name: Generate badge
      uses: jaywcjlove/coverage-badges-cli@main
      with:
        source: coverage/coverage-summary.json
        output: coverage/badge.svg
    - name: Publish coverage report and badge to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: coverage
        target-folder: coverage