name: 'run-tests'

on:
  workflow_call:

jobs:
  unit-tests:
    name: Run unit tests
    uses: ./.github/workflows/run_tests_reusable.yml
    with:
      up-flags: "--build --abort-on-container-exit"
      services: unit_tests

  integration-tests:
    name: Run integration tests
    uses: ./.github/workflows/run_tests_reusable.yml
    with:
      NODE_ENV: test_integration
      up-flags: "--build --wait"
      services: |
        db
        app
      test-command: yarn test:integration