name: 'run-tests'

on:
  workflow_call:
    inputs:
      ref:
        type: string

jobs:
  unit-tests:
    name: Run unit tests
    uses: ./.github/workflows/run_tests_reusable.yml
    with:
      up-flags: "--build --abort-on-container-exit --compatibility"
      services: unit_tests
      ref: ${{ inputs.ref }}

  integration-tests:
    name: Run integration tests
    uses: ./.github/workflows/run_tests_reusable.yml
    with:
      NODE_ENV: test_integration
      up-flags: "--build --compatibility"
      services: |
        db
        app
      test-command: yarn test:integration
      ref: ${{ inputs.ref }}
