name: Test Helm Chart

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      tag:
        type: string
        required: true

jobs:
  test-chart:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Setup infrastructure
        run: |
          #!/bin/bash

          echo "Installing Metallb..."

          # Install Metallb https://metallb.universe.tf/installation/#installation-with-helm
          helm repo add metallb https://metallb.github.io/metallb
          helm install metallb metallb/metallb \
              --namespace metallb \
              --create-namespace

          echo "Installing Nginx..."

          # Install Nginx https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
          helm upgrade --install ingress-nginx ingress-nginx \
              --repo https://kubernetes.github.io/ingress-nginx \
              --namespace ingress-nginx \
              --create-namespace

          # Wait for Nginx to finish starting up...
          while ! kubectl rollout status deployment -n ingress-nginx ingress-nginx-controller --timeout=60s; do sleep 2 ; done

          echo "Done!"

      - name: Run chart-testing (install)
        run: |
          ct install \
            --charts charts/unixpense-svc \
            --target-branch ${{ github.sha }} \
            --helm-extra-set-args "\
              --set=test.enabled=true \
              --set=image.repository=ghcr.io/${{ github.repository }} \
              --set=image.tag=${{ inputs.tag }} \
              --set=mariadb.image.registry=ghcr.io \
              --set=mariadb.image.repository=nikolayrk/containers/mariadb \
              --set=mariadb.image.tag=12.0.2 \
              --set=redis.image.registry=ghcr.io \
              --set=redis.image.repository=nikolayrk/containers/redis \
              --set=redis.image.tag=8.2.2 \
              --set=global.security.allowInsecureImages=true \
              --set=dockerRegistry.url=ghcr.io \
              --set=dockerRegistry.username=${{ secrets.DOCKERHUB_USERNAME }} \
              --set=dockerRegistry.password=${{ secrets.DOCKERHUB_PASSWORD }}"